/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View } from 'react-native';
import KeychainQ from 'react-native-keychain-q';

const server = 'https://keychain-q.example.com';
const account = 'bob';
const password = 'password';

export default class App extends Component<{}> {
  state = {
    status: 'starting',
    message: '--',
    existsAnyAccount: '',
    existsAccount: '',
    notExistsAccount: '',
    credentials: null,
  };
  componentDidMount() {
    KeychainQ.sampleMethod('Testing', 123, (message) => {
      this.setState({
        status: 'native callback received',
        message
      });
      (async () => {
        try {
          const t = await KeychainQ.fetchSupportedBiometryType();
          this.setState({biometryType: t});

          const added = await KeychainQ.setInternetPassword(server, account, password, {});
          const existsAnyAccount = await KeychainQ.containsAnyInternetPassword(server, {});
          const existsAccount = await KeychainQ.containsAnyInternetPassword(server, {account: account});
          const notExistsAccount = await KeychainQ.containsAnyInternetPassword(server, {account: 'foo'});
          const credentials = await KeychainQ.findInternetPassword(server, {account: account});
          const searched = await KeychainQ.searchInternetPasswords(server, {});
console.log(added, credentials, searched)
          this.setState({
            biometryType: t,
            existsAnyAccount: existsAnyAccount ? 'exists' : 'not exists',
            existsAccount: existsAccount ? 'exists' : 'not exists',
            notExistsAccount: notExistsAccount ? 'exists' : 'not exists',
            credentials: credentials,
          });
        } catch (error) {
          console.warn(error);
        }
      })();
    });
  }
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆KeychainQ example☆</Text>
        <Text style={styles.instructions}>STATUS: {this.state.status}</Text>
        <Text style={styles.welcome}>☆NATIVE CALLBACK MESSAGE☆</Text>
        <Text style={styles.instructions}>{this.state.message}</Text>
        <Text style={styles.welcome}>Biometry Type</Text>
        <Text style={styles.instructions}>{this.state.biometryType}</Text>
        <Text style={styles.welcome}>Password? in {server}</Text>
        <Text style={styles.instructions}>{this.state.existsAnyAccount}</Text>
        <Text style={styles.welcome}>Password? in {server} and {account}</Text>
        <Text style={styles.instructions}>{this.state.existsAccount}</Text>
        <Text style={styles.welcome}>Password? in {server} and unknown user</Text>
        <Text style={styles.instructions}>{this.state.notExistsAccount}</Text>
        <Text style={styles.welcome}>credentials in {server} and {account}</Text>
        <Text style={styles.instructions}>{this.state.credentials && ["account=", this.state.credentials.account, ", password=", this.state.credentials.password].join('') }</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
